config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :students, only: [:index, :new, :create]
  get '/student/:id', to: 'students#show', as: 'student'
end

app/models/student.rb
class Student < ActiveRecord::Base
  def to_s
    self.first_name + " " + self.last_name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  
  def index
    @students = Student.all
  end

  def show
    @student = Student.find(params[:id])
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(first_name: params[:first_name], last_name: params[:last_name])
    # @student.first_name = params[:first_name]
    # @student.last_name = params[:last_name]
    @student.save
    redirect_to @student
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Arlab</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/students/_form.html.erb
<h3>Student Form</h3>

<%= form_tag students_path do %>
  <label>First Name:</label><br>
  <%= text_field_tag :first_name %><br>

  <label>Last Name:</label><br>
  <%= text_field_tag :last_name %><br>

  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>

  <%= submit_tag "Submit Student" %>
<% end %>

app/views/students/index.html.erb
<div>
  <% @students.each do |student| %>
    <div><%= link_to student.to_s, student_path(student) %></div>
  <% end %>
</div>

app/views/students/new.html.erb
<!-- Create your form here -->
<h1>Student Form</h1>
<%= form_tag students_path do %>
  <label>First Name:</label><br>
  <%= text_field_tag :first_name %><br>

  <label>Last Name:</label><br>
  <%= text_area_tag :last_name %><br>

  <%= submit_tag "Submit Student" %>
<% end %>

app/views/students/show.html.erb
<h1><%= @student.to_s %></h1>